### ISSUE TITLE
How can I use urbridge to connect two qemu machines?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/ubridge#10]
Is there any way to involve ubridge in this from within GNS3 GUI ?

**Comment by grossmj** [comment]
Sorry no, it is not possible from within the GUI. Any reason you would like to do it?

**Comment by 1001QAdotNET** [comment]
I would like to be able to sniff the traffic between two Qemu machines.
See this: https://gns3.com/discussions/any-insights-on-the-future-netwo

**Comment by 1001QAdotNET** [comment]
I guess the same could be achieved by using the GNS3 hub but with that something like he R&S INE topology will look like hell

**Comment by noplay** [comment]
I think with new networking backend we could do that. But at this time it's not possible.
