### ISSUE TITLE
Ubridge doesn't support hostname

### ISSUE THREAD

**Issue by noplay** [GNS3/ubridge#14]
https://gns3.com/qa/gns3-dynamips-ubridge-not-fully-

**Comment by grossmj** [comment]
Name resolution works, however IPv6 is used by default on dual stack systems. I am suspecting one of the host doesn't support IPv6. One solution is to edit ``/etc/gai.conf`` and add/uncomment the following line: ``precedence ::ffff:0:0/96 100``
