### ISSUE TITLE
Version/Tag v0.9.9 has still version string 0.9.8

### ISSUE THREAD

**Issue by ehlers** [GNS3/ubridge#22]
VERSION string in ubridge.h not updated, still "0.9.8".

**Comment by noplay** [comment]
Forgot to push the master branch but seem ok in the tag: c91e5577adbabce5ceb901f8d49c9be3c900e69e

**Comment by ehlers** [comment]
I only checked the latest commit for the VERSION string. But you're right, the version/tag v0.9.9 looks fine.

Closing issue

**Comment by noplay** [comment]
I think the binary have been built with the master branch I need to check

**Comment by ehlers** [comment]
OS X binary tells, that it's version 0.9.8

**Comment by noplay** [comment]
I updated the binaries
