### ISSUE TITLE
FortiGate VM 5.4.4 with 802.1q sub-interface not work

### ISSUE THREAD

**Issue by skyjou** [GNS3/ubridge#27]
Hi~

Sub-interface with 802.1q tag in FortiGate VM 5.4.4 (KVM) on GNS3 1.5.3 doesn't work. I upgrade ubridge to version 0.9.11, but it still doesn't work. I try to create two 5.4.4 VM instances with same config in KVM by virt-manager, then connect them to same bridge. And It works well. My OS is Ubuntu 16.04. I am not sure if this issue is related to ubridge function?

**Comment by noplay** [comment]
Are you using the same virtual hardware for the network interface?

**Comment by skyjou** [comment]
Yes, I try virtio and e1000. I also try to create VM on GNS3 virtual appliance, but it dosen't work too.

**Comment by noplay** [comment]
Do you see the packet when you use wireshark on the link?

**Comment by skyjou** [comment]
Yes, I can capture packet on link.

**Comment by noplay** [comment]
And you see the 802.1q tags?

**Comment by skyjou** [comment]
Yes, but device on the other end cannot see those packets.

**Comment by noplay** [comment]
Your two node are directly connected? Nothing in the middle like a switch?

**Comment by skyjou** [comment]
If I need to capture packet between two FortiGate VM, I need to insert a dynamips switch between them. Whether there is a switch between them or not, I get same result. I use 'diag sniffer packet' command on FortiGate VM see if I can get any incoming packet, but nothing appear. When I connect FortiGate VM to IOU, on the IOU device I cannot see packet on connected port too (Using EPC to capture).

**Comment by noplay** [comment]
With 1.5.3 ubridge is not use it's a direct UDP connection between the two qemu. We start to use ubridge with 2.0. 

What is the command line use by virtmanager to start your VMs?

**Comment by skyjou** [comment]
I try 2.0RC1 too, and I see the same problem. :(

I just click 'Power On' on GUI. How can I find the command?

**Comment by noplay** [comment]
Try to start virt-manager with LIBVIRT_DEBUG=1 virt-manager --no-fork

**Comment by skyjou** [comment]
I am not sure which line will be helpful. So I upload my log and dumpxml on internet.

http://cht.tw/h/uf59l

If you cannot see the chinese character, just click the blue button at the bottom.

Thank you.

**Comment by sairuscz** [comment]
This bug is already reported. The uBridge does not allow any packets larger than 1518 bytes. You will need to lower MTU an all devices on both sides of the cloud.

**Comment by skyjou** [comment]
There is only Ping in my traffic (with some ARPs), and the packet size is small than 102 bytes. So, I think it might be two different issue?

**Comment by sairuscz** [comment]
I believe the uBridge crashes after first large packet passes through. Try to lower the MTU and see if it helps. https://github.com/GNS3/gns3-gui/issues/1867#issuecomment-284185291

**Comment by noplay** [comment]
What i don't understand is ubridge 0.9.11 should have fixed all the MTU issues because we support larger packet inside, but you seem to have the old behavior. How do you install install ubridge from packet or from source?

**Comment by skyjou** [comment]
Is this issue really related to MTU size? There should be no large packet in my environment. One interesting thing is FortiGate 5.2.X VM works well with GNS 1.5.3 or 2.0rc1. I have no idea why FortiGate 5.4  VM doesn't work.

I install ubridge 0.9.11 from source.

**Comment by skyjou** [comment]
I upload the packets capture from bridge between two KVM which are created by virt-manager.

http://cht.tw/h/0n8xf
