### ISSUE TITLE
Allow to use a TAP interface multiple time

### ISSUE THREAD

**Issue by grossmj** [GNS3/ubridge#29]
You get the following message if you attach to a TAP more than once:

```
unable to create NIO TAP for bridge 'cfc22796-ad24-4101-ab1e-eedffdf623c5-0': create_nio_tap: unable to open TAP device tap0 (Device or resource busy)
```

**Comment by grossmj** [comment]
I don't think this is possible

**Comment by lotath** [comment]
@grossmj do you have any further information regarding this? I've run into the issue on a GNS3VM with multiple users who would like access to external resource from their projects, but once a user has connected to a tap interface no-one else can use it

**Comment by noplay** [comment]
You need to create a bridge and user will create different  tap to connect to it.

**Comment by lotath** [comment]
Ah, so I've gone one step too far in creating a static tap interface. Thanks for the quick response!

**Comment by noplay** [comment]
GNS3 on Linux should create the tap interface for you if you use a bridge
in a cloud node and we correctly detect it.

**Comment by ehlers** [comment]
> GNS3 on Linux should create the tap interface for you if you use a bridge
in a cloud node and we correctly detect it.

That's good to know. Just tested it, looks very good. I've updated http://www.bernhard-ehlers.de/blog/2017/07/11/gns3-cloud-linux.html

**Comment by noplay** [comment]
How we detect bridge:
https://github.com/GNS3/gns3-server/blob/40cc5d76b33e457022f2fb2703ca9ba4e52bfa85/gns3server/utils/interfaces.py#L172
