### ISSUE TITLE
Hypervisor mode

### ISSUE THREAD

**Issue by grossmj** [GNS3/ubridge#3]
So bridges can be dynamically added/removed without reloading the config file (which is not supported on Windows because SIGHUP is not implemented on this platform).

**Comment by noplay** [comment]
And trigger a capture in real time ? And better trigger packet drop :P

On Fri, Jul 3, 2015 at 10:40 PM, Jeremy Grossmann <notifications@github.com>
wrote:

> So bridges can be dynamically added/removed without reloading the config
> file (which is not supported on Windows because SIGHUP is not implemented
> on this platform).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/ubridge/issues/3>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by grossmj** [comment]
Exactly, an hypervisor mode would allow more possibilities :)
