### ISSUE TITLE
optimize create_filter ?

### ISSUE THREAD

**Issue by Raizo62** [GNS3/ubridge#38]
Hi

To seek the bug "C99 or C11 mode" , i see the function "create_filter" of "packet_filter.c"

Will this function be more efficience if the "for" instruction exports the calcul of "lookup_table + sizeof(lookup_table) / sizeof(lookup_table[0])" in a variable before the "for" ?

**Comment by Raizo62** [comment]
closed and not modified : this is not be more efficient ?

**Comment by grossmj** [comment]
Sorry I read too fast. I thought it was same issue you reported previously.

**Comment by grossmj** [comment]
Actually while it would be little more efficient, this doesn't change much because create_filter() is only used once when you create a new filter. This function is not critical and performance is not required.

**Comment by Raizo62** [comment]
But the cost to code the export the end condition into a variable is not too expensive, also ;-)
Ok, as you wish....
