### ISSUE TITLE
IOU no connectivity after commit bbf32f7

### ISSUE THREAD

**Issue by ddragic** [GNS3/ubridge#41]
I just built GNS3 gui/server v2.0.3 and the related utilities from source and while testing noticed there is no network traffic from IOU(IOL) nodes, other types of nodes are not affected (at least the ones I tested: dynamips, qemu), wireshark shows 0 packets coming from IOU.
Since master (bf19d3a) doesn't work and tag v0.9.11 does I did a git bisect and the culprit seems to be commit bbf32f7 (Implement filter support. Fixes #16.).
This is on Linux, Fedora 24, using a local gns server.

**Comment by grossmj** [comment]
Please re-open if you still have the issue. Thanks for reporting! :+1:

**Comment by ddragic** [comment]
That was fast 😄 ...works fine now, thanks.
