### ISSUE TITLE
Windows 10 - Cloud Node Issue

### ISSUE THREAD

**Issue by paradoxxl** [GNS3/ubridge#43]
I have issues using the cloud node to connect virtual devices to the host. 

I can narrow down the problem using a simple test with the cloud node (on the host) and a VPCS:

- VPCS on host, connected to VMWare or VirtualBox hostonly adapter: Connection successful
- VPS on GNS3 VM, connected to VMWare or VirtualBox hostonly adapter: Connection **un**successful

Therefore, I think the problem is somewhere in the connection through the GNS3 VM. 

I tried several versions of pcap and npcap with both installed, only winpcap or only npcap with compatibility mode. I also tried using different versions of ubridge (0.9.10,0.9.11,0.9.13). Using different GNS3 versions (2.0.0,2.0.3,2.1.0b1) also didn't result in any success. 

More details on the connectivity tests I did: [GNS3 forum](https://gns3.com/qa/connection-problems-cloud-ethern)

Thanks,
Dominik

**Comment by grossmj** [comment]
I am going to investigate this.

Thanks,
Jeremy

**Comment by grossmj** [comment]
It is possible to use the host-only adapter from within the VM. Please use a bridged adapter instead. Please see https://github.com/GNS3/gns3-gui/issues/534
