### ISSUE TITLE
[Cosmetic] ubridge -v looks strange

### ISSUE THREAD

**Issue by ehlers** [GNS3/ubridge#46]
As ubridge since 0.13 always shows the version on startup, `ubridge -v` gives a little strange output:
```
/Users/behlers/GNS3/source/ubridge# ./ubridge -v
uBridge version 0.9.13 running with libpcap version 1.5.3 - Apple version 54
ubridge version 0.9.13
```

Maybe ubridge -v could just exit, as the version is already shown. But I don't know, if GNS3 parses the output. But then the first line could result in some unwanted bugs.

**Comment by ehlers** [comment]
Just checked the ubridge version check in gns3-server. It checks the word after the first occurrence of "ubridge version", so gets the version from the second line. The first line doesn't match as there uBridge has a capital "B". So for the version check in gns3-server, the second line needs to stay.

**Comment by grossmj** [comment]
Indeed, we should not display that first line when -v is used.
