### ISSUE TITLE
ubridge 0.9.13 (GNS 2.1.11) doesn't work with tap interfaces on OS X

### ISSUE THREAD

**Issue by mideoye** [GNS3/ubridge#55]
Hi there,

It appears ubridge 0.9.13 is unable to detect and run tap interfaces for GNS 2.1.11 MacOS 10.14.2. I started GNS3 as root and when I set up a test project with a Cisco IOS router and cloud/tap interface on the local OS X, I get the following error when I attempt to connect the router to the cloud's tap interface:

Error while sending command 'bridge add_nio_tap 5c076a45-9514-4f40-996a-3cf29b80f03b-5 "/dev/tap4"': unable to create NIO TAP for bridge '5c076a45-9514-4f40-996a-3cf29b80f03b-5': uBridge version 0.9.13 running with libpcap version 1.8.1 -- Apple version 79.200.4
Hypervisor TCP control server started (IP 127.0.0.1 port 57658).
UDP tunnel connecting from local port 10001 to IPv4 addresss 127.0.0.1 on port 10000
create_nio_tap: unable to open TAP device /dev/tap4 (No such file or directory)

<img width="1440" alt="screenshot 2019-01-12 at 00 27 17" src="https://user-images.githubusercontent.com/46613547/51066436-0c159f00-1602-11e9-801d-9a84caad5ffd.png">

Tap interface driver installed is tun tap and I've been able to manually bring up the tap interfaces and assign IPs for respective tap interfaces and it all works fine. So the issue appears to be with ubridge. Is this a known issue? Please is there a fix or workaround?

**Comment by grossmj** [comment]
It looks like /dev/tap4 doesn't exist in the screenshot. A workaround could be to just use tap4 in the cloud configuration and the TAP interface should automatically be created.

**Comment by mideoye** [comment]
Thanks a lot for your suggestion, that seems to work now and the tap interface came up. Stumbled on another issue now, while I'm able to ping the GNS3 router from OS X terminal via the tap interface, I'm unable to ping the tap interface from the perspective of the GNS3 router. Is this normal?
