### ISSUE TITLE
Missing bionic package in unstable

### ISSUE THREAD

**Issue by adosztal** [GNS3/ubridge#56]
The ubridge package for bionic is missing from the [repository](https://launchpad.net/~gns3/+archive/ubuntu/unstable).

**Comment by adosztal** [comment]
I've just noticed the same applies to gns3-iou.

**Comment by grossmj** [comment]
Thanks, going to fix this.

**Comment by grossmj** [comment]
It should be alright now. Thanks for catching this.

https://launchpad.net/~gns3/+archive/ubuntu/unstable/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic
