### ISSUE TITLE
Problems/ problema

### ISSUE THREAD

**Issue by pipefg** [GNS3/ubridge#57]
Sorry my English 
I have problems 
Hello, I have the following problem. 
 
I get this message 
 

Bridge requires root access or capability to interact with network adapters

 I'm using Palo Alto vmware 

What Do I?

**Comment by grossmj** [comment]
What is your operating system, Linux?

**Comment by pipefg** [comment]
Mac OS mojave

**Comment by grossmj** [comment]
Open a terminal and type the following commands

sudo chown root:admin /Application/GNS3.app/Contents/MacOS/ubridge
sudo chmod 4750 /Application/GNS3.app/Contents/MacOS/ubridge

Then restart GNS3.

**Comment by pipefg** [comment]
Thank you. I'm gonna try that.

**Comment by pipefg** [comment]
Funciono!! 
I me work. thank you very much. only remplace  MacOS for resources
sudo chown root:admin /Applications/GNS3.app/Contents/Resources/ubridge
sudo chmod 4750 /Applications/GNS3.app/Contents/Resources/ubridge

**Comment by grossmj** [comment]
Glad it worked 👍

**Comment by mpeguero** [comment]
I tried it:: /Applications/GNS3.app/Contents/Resources/ubridge: No such file or directory
