### ISSUE TITLE
ubridge OS X binary of release 0.9.16 shows version 0.9.17

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/ubridge#62]
The OS X binary of release 0.9.16 shows version 0.9.17. As this binary is also included in the OS X package of GNS3 v2.1.19 (GNS3-2.1.19.dmg) the GNS3 package is also affected.

While this doesn't result in any bugs, it's quite unfortunate, that one can't rely on the version string displayed.

```
/Users/behlers# Downloads/ubridge-osx 
uBridge version 0.9.17 running with libpcap version 1.8.1 -- Apple version 79.20.1
```

The Linux binary shows the correct version string, I haven't checked the windows binary.

**Comment by grossmj** [comment]
Indeed, that is unfortunate, I will check what happened. The Windows binary shows the correct version.

**Comment by grossmj** [comment]
Looks like the development version was mistakenly uploaded last time, this process is done manually... guess we need automate this part just like we do for GNS3.

Please can you try if this is correct now? https://github.com/GNS3/ubridge/releases/tag/v0.9.16

**Comment by b-ehlers** [comment]
Looks good now.

```
/Users/behlers# Downloads/ubridge-osx 
uBridge version 0.9.16 running with libpcap version 1.8.1 -- Apple version 79.20.1
```

**Comment by grossmj** [comment]
Thanks :+1:
