### ISSUE TITLE
Ploblmes in gns3

### ISSUE THREAD

**Issue by pipefg** [GNS3/ubridge#65]
Sorry my English
I have problems
Hello, I have the following problem.

MacOS Mojave
I receive this message when connecting the Switch L2"default" to the cloud
> Server error from http://127.0.0.1:8000: SW1: unable to create generic ethernet NIO

**Comment by grossmj** [comment]
You should have seen a dialog box asking to set permissions for uBridge when starting GNS3 the first time. Here is how to do it manually from a terminal.

```
sudo chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge
sudo chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge
```

![Screenshot from 2019-12-14 14-43-55](https://user-images.githubusercontent.com/4752614/70844745-31e59c80-1e80-11ea-8fbd-398388db486f.png)

**Comment by pipefg** [comment]
I already tried that and it doesn't work either

**Comment by GMarciales** [comment]
Pipefg,

Would you please share the output of the **ls -l** command shared previously?

Best

GM

**Comment by pipefg** [comment]
where to apply that

**Comment by pipefg** [comment]
drwxr-xr-x   7 felipe  staff   224 Dec 14 19:42 GNS3

**Comment by GMarciales** [comment]
Hi,

Your output shows a letter D, which means = directory. Would you please share a screenshot instead copy and paste.
Kindly, take a look what grossmj shared.

Best

GM

**Comment by pipefg** [comment]
I occupied version 1.4.2 on mac. It is in that version where it does not work. The current ones do work. but I'm interested in 1.4.2

**Comment by pipefg** [comment]
elipe@F3lipeX ~ % ls -l /Applications/GNS3.app/Contents/MacOS/ubridge 
-rwsr-x---  1 root  admin  89840 Nov 12 04:52 /Applications/GNS3.app/Contents/MacOS/ubridge

**Comment by GMarciales** [comment]
The output misses the @, would be more easy if you share a screenshot instead

**Comment by pipefg** [comment]
![Captura de Pantalla 2019-12-14 a la(s) 23 38 43](https://user-images.githubusercontent.com/49672169/70857313-e3112480-1eca-11ea-8407-daf3d50e02c1.png)

**Comment by GMarciales** [comment]
Look, it is not exactly like the one shared by @grossmj .

Please run the commands:

sudo chown root:admin /Applications/GNS3.app/Contents/MacOS/ubridge

sudo chmod 4750 /Applications/GNS3.app/Contents/MacOS/ubridge

one line at a time

Saludos

**Comment by pipefg** [comment]
I already did that procedure. and still it doesn't work

**Comment by GMarciales** [comment]
I am trying to help, but I am not an Apple (BSD) expert. I run Linux in my computers instead, and it works perfect.

![Screenshot from 2019-12-14 20-49-02](https://user-images.githubusercontent.com/15690019/70857439-b7cf0b00-1eb3-11ea-84ca-51a1660b965a.png)

**Comment by pipefg** [comment]
I get it. First time version 1.4.2 gives me trouble.
It all started after formatting.
I will have to get used to a more recent version

**Comment by pipefg** [comment]
friend, I managed to repair it. But I don't know what I did. What I did was install several versions and from nowhere I boot.
but thank you very much for your contributions

**Comment by pipefg** [comment]
but I think it is related to homebrew.
install telnet and openssh and the bridge disappeared.
PROBLEM SOLVED
