### ISSUE TITLE
Duplicated Received Packets, How to Solve it?

### ISSUE THREAD

**Issue by SalarJamal** [GNS3/ubridge#76]
I am working on scenario of one switch and two VM hosts connected to it, when the first host send request to the second host it arrives duplicated, also the acknowledgement returned back duplicated! how to solve this issue?
 notes:
GSN3 installed on Windows 10
left-side picture= sender, 
right-side picture = receiver
![Untitled](https://user-images.githubusercontent.com/90519454/161825940-37241c46-2503-42ec-bab4-0628b3ccbb81.jpg)

**Comment by grossmj** [comment]
This is an issue with winpcap and vmnet interfaces on Windows. Please activate "block network traffic originating from the host OS" in the preferences.

![Screenshot from 2022-04-06 11-12-53](https://user-images.githubusercontent.com/4752614/161888872-0aba8d37-b49c-4037-90c4-706b72ebaf01.png)

**Comment by SalarJamal** [comment]
I activated it but the same issue remain not solved. 
Note: 
this issue occur only with application protocol based UDP.
