### ISSUE TITLE
ubridge missing from -unstable packages

### ISSUE THREAD

**Issue by athompson-merlin** [GNS3/ubridge#91]
As of 2024-Apr-03, ubridge is present in the "stable" PPA tree for Ubuntu "jammy", but not the "unstable" tree.  This causes the gns3 installation script to fail when gns3-server is unable to pull in the ubridge dependency.
The workaround is manual, but simple enough - include both stable and unstable repos in apt sources.
The theoretically-correct fix is to automatically generate a 'ubridge' .deb as part of the "unstable" gns3 PPA repo.

**Comment by grossmj** [comment]
@athompson-merlin thanks, I have added the missing packages for Ubuntu "jammy".

https://launchpad.net/~gns3/+archive/ubuntu/unstable/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy
